# Generated by Django 3.1.1 on 2020-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
