# Generated by Django 3.1.1 on 2020-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
