# Generated by Django 3.1.1 on 2020-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_orderlist_orderpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='slipTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
