# Generated by Django 3.1.1 on 2020-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200927_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
