# Generated by Django 3.1.1 on 2020-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orderpending_trackingnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m001', models.FloatField()),
                ('m002', models.FloatField()),
                ('m003', models.FloatField()),
                ('m004', models.FloatField()),
                ('m005', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p001', models.FloatField()),
                ('p002', models.FloatField()),
                ('p003', models.FloatField()),
                ('p004', models.FloatField()),
                ('p005', models.FloatField()),
            ],
        ),
    ]
