# Generated by Django 3.1.1 on 2020-12-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201219_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('m1', models.FloatField(blank=True, null=True)),
                ('m2', models.FloatField(blank=True, null=True)),
                ('m3', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
