# Generated by Django 3.1.1 on 2021-02-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
